mysite-house/account/urls.py
from django.urls import path
from .views import *

app_name = 'account'
urlpatterns = [
    path('login/', user_login, name='login'),
    path('logout/', logout, name="logout"),  # Log out
    path('register/', register, name='register'),  # Register
    path('center/', center, name='center'),
    path('change_profile/', change_profile, name='change_profile'), # Modify the data
]

mysite-house/mysite/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static
from mysite import settings
from house.views import *

urlpatterns = [
    path('captcha/', include('captcha.urls')), # Verification code
    path('', index, name='index'),
    path('detail/<int:bid>', detail, name='detail'),
    url(r'new_search$', new_search, name='new_search'),
    url(r'^search$', search, name='search'),
    path('rent/', rent, name='rent'), # To apply for
    path('unsubscribe/<int:rid>', unsubscribe, name='unsubscribe'), # unsubscribe
    path('cancel_unsub/<int:cid>', cancel_ubsub, name='cancel_unsub'), # cancel unsubscribe
    path('delay/<int:rid>', delay, name='delay'),
    path('account/', include('account.urls'), name='account'),
    path('user/', include('user.urls'), name='user'),
    path('admin/', admin.site.urls),
    re_path(r'^admin_tools/', include('admin_tools.urls')), # admin_tools
    path('tongji/', tongji, name='tongji'),
    path('profit_search/', profit_search, name='profit_search'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL) # Configure the path to the static resource

mysite-house/user/urls.py
from django.urls import path
from .views import *

app_name = 'user'

urlpatterns = [
    path('login/', user_login, name='login'),
    path('register/', register, name='register'), # register
    path('change_profile/', change_password, name='change_profile'), # Modify personal information
    path('logout/', logout, name='logout'), # exit
]

mysite-house/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>House Booking System</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{% static '/css/bootstrap.css' %}" rel="stylesheet">
    

    <!-- <script src="{% static '/js/jquery.js' %}"></script> -->
    <script src="https://cdn.bootcdn.net/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <script src="{% static '/js/bootstrap.js' %}"></script>

     
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
    <link rel="stylesheet" href="https://unpkg.com/bootstrap-table@1.15.3/dist/bootstrap-table.min.css">


    <link href="{% static '/layer/layer/theme/default/layer.css' %}" rel="stylesheet">
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.1/moment.min.js" integrity="sha512-qTXRIMyZIFb8iQcfjXWCO8+M5Tbc38Qi5WzdPOYZHIlZpzBHG3L3by84BBBOiRGiEb7KKtAOAs5qYdUiZiQNNQ==" crossorigin="anonymous"></script>
    <link href="https://cdn.bootcdn.net/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css" rel="stylesheet">
    <script src="https://cdn.bootcdn.net/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js"></script>

        <style type="text/css">
      body {
        padding-top: 50px;
        padding-bottom: 40px;
        <!--background-color: #A9F5BC;-->
      }
      .page_a {
          color:#444;text-decoration:none;
      }
      * {
        /*font-size: large;*/
      }
      .divcss6{
          position:relative;
          color:#F00;
          font-size: 25px;
      }

    </style>

</head>
<body>
<!--style="background-image:url(../static/Background2.jpg"-->
    <style type="text/css">
      body {
      background-image:url(../static/Background2.jpg);
      background-repeat:no-repeat;
      background-position:center;
      background-attachment:fixed;
      }
    </style>
<nav class="navbar navbar-default navbar-fixed-top" style="padding-top:10px; font-size:25px;">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
       <a class="" href="/">
          <img src="/static/Logo2.jpg" alt="" class="img-rounded" style="height:50px;">
      </a>
<!--        <a href="/" class="navbar-brand">Farm Booth Booking</a>-->

    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="{% url 'new_search' %}">Search</a></li>


      </ul>


        <ul class="nav navbar-nav navbar-right">
            {% if request.user.is_authenticated %}
                <li><a href="{% url 'account:center' %}">Hello, {{ request.user.username }}</a></li>
                <li><a href="{% url 'account:center' %}">User Center</a></li>
                <li><a href="{% url 'user:change_profile' %}">Change Profile</a></li>
                <li><a href="{% url 'user:logout' %}">Logout</a></li>

            {% else %}
            <li><a href="/admin/login">Admin Login</a></li>
                <li><a href="{% url 'user:login' %}">Login</a></li>
                <li><a href="{% url 'user:register' %}">Register</a></li>
            {% endif %}
        </ul>

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<div id="content" class="container">
    <div class="message-area">
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{% if message.tags == 'error' %}danger{% else %}success{% endif %}">{{ message }}</div>
            {% endfor %}
        {% endif %}
    </div>
  {% block content %}
  {% endblock %}
  <hr>
  <footer>
<p>&copy; House Booking System 2021</p>
</footer>
</div>

<script src="https://unpkg.com/bootstrap-table@1.15.3/dist/bootstrap-table.min.js"></script>
<script src="{% static '/layer/layer/layer.js' %}"></script>

</body>
</html>