mysite-house/account/urls.py
from django.urls import path
from .views import *

app_name = 'account'
urlpatterns = [
    path('login/', user_login, name='login'),
    path('logout/', logout, name="logout"),  # Log out
    path('register/', register, name='register'),  # Register
    path('center/', center, name='center'),
    path('change_profile/', change_profile, name='change_profile'), # Modify the data
]

mysite-house/mysite/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static
from mysite import settings
from house.views import *

urlpatterns = [
    path('captcha/', include('captcha.urls')), # Verification code
    path('', index, name='index'),
    path('detail/<int:bid>', detail, name='detail'),
    url(r'new_search$', new_search, name='new_search'),
    url(r'^search$', search, name='search'),
    path('rent/', rent, name='rent'), # To apply for
    path('unsubscribe/<int:rid>', unsubscribe, name='unsubscribe'), # unsubscribe
    path('cancel_unsub/<int:cid>', cancel_ubsub, name='cancel_unsub'), # cancel unsubscribe
    path('delay/<int:rid>', delay, name='delay'),
    path('account/', include('account.urls'), name='account'),
    path('user/', include('user.urls'), name='user'),
    path('admin/', admin.site.urls),
    re_path(r'^admin_tools/', include('admin_tools.urls')), # admin_tools
    path('tongji/', tongji, name='tongji'),
    path('profit_search/', profit_search, name='profit_search'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL) # Configure the path to the static resource

mysite-house/user/urls.py
from django.urls import path
from .views import *

app_name = 'user'

urlpatterns = [
    path('login/', user_login, name='login'),
    path('register/', register, name='register'), # register
    path('change_profile/', change_password, name='change_profile'), # Modify personal information
    path('logout/', logout, name='logout'), # exit
]

mysite-house/house/models.py
import datetime
from django.contrib.auth.models import User
from django.db import models


# Create your models here.
class House(models.Model):
    """
    House table
    """
    #Define the field for the name of the house
    name = models.CharField(max_length=32, verbose_name='name')
    # ImageField: Inherit from FileField to validate the uploaded content to make sure it is a valid image
    # Upload the image
    #Define the picture of the house in this field
    picture = models.ImageField(upload_to='houses')
    #Define the description of the house in this field
    description = models.TextField(verbose_name='detail')
    # Define the area of the house in this field
    area = models.FloatField(verbose_name='area')
    # Define the price of the house in this field
    price = models.FloatField(verbose_name='price(permonth)')
    # Define the position of the house in this field
    position = models.CharField(max_length=64, verbose_name='position')
    # Define the create time of the house in this field
    create_at = models.DateTimeField(auto_now_add=True, verbose_name='online time')

    # The current status of house information
    # TODO status Not rent | have for rent
    STATUS_CHOICES = (
        ('wait to rent', 'wait to rent'),
        ('rented', 'rented'),
    )

    status = models.CharField(max_length=32, verbose_name='status', choices=STATUS_CHOICES, default='wait to rent')
    # update time
    update_time = models.DateTimeField(verbose_name='update time', auto_now=True)

    @property
    def deadline(self):
        """
        Display expiration time
        """
        # Find the current rent
        if self.status == 'rented':
            # Find the most recent rental
            lastest_rent = self.rent_set.last()
            status = lastest_rent.status
            if status in ['normal', 'delayed', 'apply to unsubscribe']:
                return lastest_rent.deadline
            else:
                return 'wait to rent'
        else:
            return 'wait to rent'

    class Meta:
        verbose_name = 'house'
        verbose_name_plural = verbose_name
        ordering = ('-create_at',)

    def __str__(self):
        return str(self.name)


class Rent(models.Model):
    """
    Rent
    """
    house = models.ForeignKey(House, on_delete=models.CASCADE, verbose_name='House')
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='User', related_name="h_rent_user")
    create_at = models.DateTimeField(auto_now_add=True, verbose_name='rent time')
    # Lease duration
    months = models.IntegerField(verbose_name='rent_months', default=1)
    # Expiry Time
    deadline = models.DateField(verbose_name='deadline')
    money = models.FloatField(verbose_name='total money', default=0)
    STATUS_CHOICES = (
        ('normal', 'normal'),
        ('apply to unsubscribe', 'apply to unsubscribe'),
        ('unsubscribed', 'unsubscribed'),
        ('delayed', 'delayed'),
    )
    # Unsubscribe needs to be reviewed by the administrator
    status = models.CharField(max_length=32, verbose_name='status', choices=STATUS_CHOICES, default='normal')

    @property
    def total_money(self):
        """
        Total price
        """
        return self.months * self.house.price

    @property
    def is_deadline(self):
        """
        Whether or not on the deadline
        :return:
        """
        return datetime.datetime.now().date() >= self.deadline

    @property
    def current_status(self):
        """
        Current state
        1. The lease
        2. Lease cancellation has been applied for
        3. Succeeded
        4. Continue to postpone
        :return:
        """
        pass
        # TODO

    class Meta:
        verbose_name = 'rent'
        verbose_name_plural = verbose_name
        ordering = ('-create_at',)

    def __str__(self):
        return f'{self.house.name} - {self.user.username} - {self.create_at}'


class Unsubscribe(models.Model):
    """
    Unsubscribe information form
    """
    rent = models.OneToOneField(Rent, on_delete=models.CASCADE, verbose_name='rent info')
    create_at = models.DateTimeField(auto_now_add=True, verbose_name='rent time')
    STATUS_CHOICES = (
        ('wait to approve', 'wait to approve'),
        ('approve', 'approve'),
    )
    # Unsubscribe needs to be reviewed by the administrator
    status = models.CharField(max_length=32, verbose_name='status', choices=STATUS_CHOICES)
    # update time
    update_time = models.DateTimeField(verbose_name='update time', auto_now=True)
    # Whether to come from the delay
    is_from_delay = models.BooleanField(verbose_name='is from delay', default=False)
    class Meta:
        verbose_name = 'subscribe'
        verbose_name_plural = verbose_name
        ordering = ('-create_at',)

    def __str__(self):
        return str(self.rent)


class Delay(models.Model):
    """
    Delay
    """
    rent = models.ForeignKey(Rent, on_delete=models.CASCADE, verbose_name='rent info')
    create_at = models.DateTimeField(auto_now_add=True, verbose_name='create time')
    # Lease duration
    months = models.IntegerField(verbose_name='rent_months', default=1)
    # Extension Time
    deadline = models.DateField(verbose_name='deadline')
    money = models.FloatField(verbose_name='total money', default=0)
    class Meta:
        verbose_name = 'delay'
        verbose_name_plural = verbose_name
        ordering = ('-create_at',)

    def __str__(self):
        return str(self.rent)

class Tongji(models.Model):
    class Meta:
        verbose_name = 'Statistics'
        

mysite-house/house/views.py
import datetime

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.shortcuts import render, get_object_or_404, redirect, HttpResponse
from .models import *
from .filters import *
from .tables import *
import json
from django.db.models import Sum

class DateEncoder(json.JSONEncoder):
    def default(self, obj):
        if isinstance(obj, datetime.datetime):
            return obj.strftime("%Y-%m-%d %H:%M:%S")
        else:
            return json.JSONEncoder.default(self, obj)

# Create your views here.
def index(request):
    """
    mainpage
    :param request:
    :return:
    """
    latest = House.objects.all()[:4]
    return render(request, 'house/index.html', {'latest': latest})


def detail(request, bid):
    """
    detail
    :param request:
    :return:
    """
    house = get_object_or_404(House, id=bid)
    return render(request, 'house/detail.html', {'house': house})

#The search function
def search(request):
    """
    retrieve
    :param request:
    :return:
    """
    # TODO PAGE
    
    #Define search filters
    f = HouseFilter(request.GET, queryset=House.objects.all())
    #Data table is a JS jump list display
    table_data = json.dumps(list(f.qs.values()), cls=DateEncoder)
    #Rendering to return to the search page
    return render(request, 'house/search.html', {'filter': f, 'table_data': table_data})
#New Search Functions
def new_search(request):
    #Sort houses
    sort = request.GET.get('sort', '-1')
    #Specify how to sort
    if sort == '-1':
        qs = House.objects.all()
    else:
        qs = House.objects.all().order_by(sort)
    #Filter to select eligible stalls
    f = HouseFilter(request.GET, queryset=qs)
    #Displays the retrieved data
    qs = f.qs
    #Present data in tabular form
    table = HouseTable(qs)
    #Back to the search page
    return render(request, 'house/new_search.html', {'filter': f, 'table': table})




@transaction.atomic
@login_required
def rent(request):
    """
    Rent
    :param request:
    :param bid:
    :return:
    """
    #Get the number of the rented house
    bid = request.POST.get('bid')
    #Error handling, return 404 when no data is available
    house = get_object_or_404(House, id=bid)
    #Lets say this house has been rented out when its status bit is' rented '
    if house.status == 'rented':
        messages.error(request, 'already rented')
        #Back to main page
        return redirect('/')
    #The status of the assignment house is' rented '
    house.status = 'rented'
    #Save the current state of the house
    house.save()
    #Defining the current leased house, the user is the user who rents a house
    rent = Rent(house=house, user=request.user)
    #Deadline for obtaining house rental
    rent.deadline = request.POST.get('deadline')
    #Obtain the rental period of the house
    rent.months = int(request.POST.get('months'))
    #Calculate the rent of the house
    rent.money = rent.months * rent.house.price
    #Save the attributes of the house
    rent.save()
    #Indicates that the user has rented successfully
    messages.success(request, 'You have rented it !')
    #Back to main page
    return redirect('/')


@transaction.atomic
@login_required
def unsubscribe(request, rid):
    """
    unsubscribe
    :param request:
    :return:
    """
    rent = get_object_or_404(Rent, id=rid)
    if rent.deadline < datetime.datetime.now().date():
        messages.error(request, 'your rent is out of time!')
        redirect('/account/center')
    else:
        rent.status = 'apply to unsubscribe'
        rent.save()
        unsub = Unsubscribe(rent=rent)
        _from = request.GET.get('from', '-1')
        if _from == 'delay':
            unsub.is_from_delay = True
        unsub.status = 'wait to approve'
        unsub.save()
        messages.success(request, 'action ok!')
        return redirect('/account/center')


@transaction.atomic
@login_required
def cancel_ubsub(request, cid):
    # TODO Logic from delay to unsubscribe
    """
    delay->unsubscribe


    :param request:
    :param cid:
    :return:
    """
    ubsub = get_object_or_404(Unsubscribe, id=cid)

    if ubsub.is_from_delay: # From Renewal
        ubsub.rent.status = 'delayed'
    else:
        ubsub.rent.status = 'normal'

    ubsub.rent.save()
    ubsub.delete()
    messages.success(request, 'cancel ok!')
    return redirect('/account/center/')


@transaction.atomic
@login_required
def delay(request, rid):
    """
    delay
        rent: normal You can do that in state
    :param request:
    :param rid:
    :return:
    """
    rent = get_object_or_404(Rent, id=rid)
    if rent.status != 'normal':
        messages.error(request, f'this rent info is {rent.status}, can not delay!')
        return redirect('/account/center/')
    if request.method == 'GET':
        return render(request, 'house/delay.html', {'rent': rent, 'house': rent.house})
    elif request.method == 'POST':
        d = Delay(rent=rent)
        deadline = request.POST.get('deadline')
        months = request.POST.get('months')
        # rent Information update
        rent.status = 'delayed'
        rent.deadline = deadline
        rent.months = months
        rent.money = int(rent.months) * rent.house.price
        rent.save()
        # # house Information update
        # house = rent.house
        # house.deadline = deadline
        # house.save()
        # delay Information update
        d.deadline = deadline
        d.save()
        messages.success(request, 'delay ok!')
        return redirect('/account/center/')

def tongji(request):
    """
    statistical
The contract
● Number of contracts awaiting review
● Number of contracts due

The house
● Total number of houses
● Number of empty houses
● Number of leased houses

profit
● this month the total income of the rent (the rent of each month income can be expressed in a broken line statistical chart, this is all right, see the master design how to do it)
● The rent of the current year's income
    """
    now = datetime.datetime.now()
    contacts = {
        'wait_to_approve': Unsubscribe.objects.filter(status='wait to approve', create_at__month=now.month).count(),
        'deadline': Rent.objects.filter(deadline__lt=now.date()).count(),
        'delay': Rent.objects.filter(status='delayed').count(),
    }
    
    houses = {
        'total': House.objects.all().count(),
        'empty': House.objects.filter(status='wait to rent').count(),
        'used': House.objects.filter(status='rented').count(),
    }

    
    month_money = Rent.objects.filter(create_at__month=now.month).exclude(status='unsubscribed').aggregate(Sum('money'))['money__sum']
    if month_money is None:
        month_money = 0

    year_money = Rent.objects.filter(create_at__year=now.year).exclude(status='unsubscribed').aggregate(Sum('money'))['money__sum']
    if year_money is None:
        year_money = 0
    
    delay_money = Delay.objects.filter(create_at__year=now.year, rent__status='delayed').aggregate(Sum('money'))['money__sum']
    if delay_money is None:
        delay_money = 0

    profits = {
        'month': month_money,
        'year': year_money + delay_money
    }

    return render(request, 'house/tongji2.html', {'contacts':contacts, 'houses': houses, 'profits': profits})

def profit_search(request):
    """
    profit_search
    """
    qs = Rent.objects.exclude(status='unsubscribed')
    start = request.GET.get('start', '').strip()
    end = request.GET.get('end', '').strip()
    if start != '':
        start = datetime.datetime.strptime(start, '%m/%d/%Y')
        qs = qs.filter(create_at__gt=start)
    if end != '':
        end = datetime.datetime.strptime(end, '%m/%d/%Y')
        qs = qs.filter(create_at__lt=end)
    total_profit = qs.aggregate(Sum('money'))['money__sum']
    if total_profit is None:
        total_profit = 0
    return render(request, 'house/profit_search.html', {'qs': qs, 'p': total_profit})

mysite-house/templates/house/delay.html
{% extends "base.html" %}
{% block content %}
    <h1>Delay</h1>
    <div class="row">
        <div class="col-md-5">
            <img  src="/media/{{ house.picture }}" alt="" class="img-responsive img-thumbnail center-block">
        </div>
        <div class="col-md-7">
            <ul class="list-group">
                <li class="list-group-item">Name: {{ house.name }}</li>
                <li class="list-group-item">Price: <span class="h4">{{ house.price }}</span></li>
                <li class="list-group-item">Position: {{ house.position }}</li>
                <li class="list-group-item">Area: {{ house.area }}</li>
                <li class="list-group-item">Publish at: {{ house.create_at }}</li>
                <li class="list-group-item text-center">
                    <button class="btn btn-primary" data-toggle="modal" data-target="#myModal">Delay</button>

                </li>
            </ul>
        </div>
    </div>
    <h3>Detail</h3>
    <div>
        {{ house.description }}
    </div>

    <!--  The terms of the contract -->
    <div class="modal fade" tabindex="-1" role="dialog" id="myModal">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title">Contract</h4>
                </div>
                <div class="modal-body">
                    <!-- TODO Article 1 of Contract -->
                    {% include 'house/hetong.html' %}
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary" onclick="showQrCode()">I agree</button>
                </div>
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->
    <!--  /The terms of the contract -->
    <!-- Payment QR code -->
        <div class="modal" tabindex="-1" role="dialog" id="payModal">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title">Qr Code</h4>
                    </div>
                    <div class="modal-body">
                        <div>
                            <img src="/static/pay_qrcode.png" class="img-responsive center-block" alt="">
                        </div>
                        <div>
                            <form class="form" id="pay-form" method="post" action="{% url 'delay' rent.id %}">
                                <div class="form-group">
                                    <label for="">Lease duration (months)</label> <!-- The length of lease -->
                                    <input id="months" name="months" type="number" min=1, max=12 class="form-control" required>
                                </div>
                                <div class="form-group">
                                    <label for="">DeadLine</label>
                                    {% csrf_token %}
                                    <input id="deadline" type="date" name="deadline" class="form-control" readonly/>
                                    <input type="hidden" name="bid" value="{{ house.id }}">
                                </div>
                                <div class="form-group">
                                    <label for="">Total Money</label>
                                    <input type="text" class="form-control" readonly id="total_money">
                                </div>

                            </form>
                        </div>

                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        <button type="button" class="btn btn-success" onclick="pay()">Pay</button>
                    </div>
                </div><!-- /.modal-content -->
            </div><!-- /.modal-dialog -->
        </div>
    <!-- /Payment QR code -->
    <script>
        function showQrCode() {
            $('#myModal').modal('hide');
            // Pop-up QR code
            $('#payModal').modal('show');
        }
        function pay() {
            /**
             * pay
             */
            if(!$('#months').val()) {
                alert('Please Input the Months!');
                return false;
            }
            $('#pay-form').submit();
        }
        var price = {{ house.price }};
        $('#months').blur(function(){
            var months = parseInt($(this).val());
            if (months <= 0) {
                alert('please input the months > 0');
                return false;
            }
            var dealine = moment('{{ rent.deadline }}').add(months, 'month');
            $('#deadline').val(dealine.format('YYYY-MM-DD'));
            var r_price = price * months;
            $('#total_money').val(r_price);
        });
    </script>
{% endblock %}

mysite-house/templates/house/detail.html
{% extends "base.html" %}
{% block content %}
    <div class="row" style="padding-top:120px;">
        <div class="col-md-5">
            <img  src="/media/{{ house.picture }}" alt="" class="img-responsive img-thumbnail center-block">
        </div>
        <div class="col-md-7">
            <ul class="list-group">
                <li class="list-group-item">Name: {{ house.name }}</li>
                <li class="list-group-item">Price: <span class="divcss6">GBP £ {{ house.price }}</span></li>
                <li class="list-group-item">Position: {{ house.position }}</li>
                <li class="list-group-item">Area: {{ house.area }}</li>
                <li class="list-group-item">Publish at: {{ house.create_at }}</li>
                <li class="list-group-item text-center">
                    <!-- TODO Rent -->
                    {% if request.user.is_authenticated %}
                        {% if house.status == 'rented' %}
                            <button class="btn btn-danger" disabled>Have Rented</button>
                            {% else %}
                            <button class="btn btn-primary" data-toggle="modal" data-target="#myModal">Rent</button>
                        {% endif %}
                        {% else %}
                            <a href="#" class="btn btn-danger">Please Login First</a>
                            <a href="{% url 'account:login' %}" class="btn btn-primary">Login</a>
                    {% endif %}
                </li>
            </ul>
        </div>
    </div>
    <h3>Detail</h3>
    <div>
        {{ house.description }}
    </div>

    <!--  The terms of the contract -->
    <div class="modal fade" tabindex="-1" role="dialog" id="myModal">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title">Contract</h4>
                </div>
                <div class="modal-body">
                    <!-- TODO Article 1 of Contract -->
                    {% include 'house/hetong.html' %}
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary" onclick="showQrCode()">I agree</button>
                </div>
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->
    <!--  /he terms of the contract -->
    <!-- Payment QR code -->
        <div class="modal" tabindex="-1" role="dialog" id="payModal">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title">Qr Code</h4>
                    </div>
                    <div class="modal-body">
                        <div>
                            <img src="/static/pay_qrcode.png" class="img-responsive center-block" alt="">
                        </div>
                        <div>
                            <form class="form" id="pay-form" method="post" action="{% url 'rent' %}">
                                <div class="form-group">
                                    <label for="">Lease duration (months)</label> <!-- The length of lease -->
                                    <input id="months" name="months" type="number" min=1, max=12 class="form-control">
                                </div>
                                <div class="form-group">
                                    <label for="">DeadLine</label>
                                    {% csrf_token %}
                                    <input id="deadline" type="date" name="deadline" class="form-control" readonly/>
                                    <input type="hidden" name="bid" value="{{ house.id }}">
                                </div>
                                <div class="form-group">
                                    <label for="">Total Money</label>
                                    <input type="text" class="form-control" readonly id="total_money">
                                </div>
                                
                            </form>
                        </div>

                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        <button type="button" class="btn btn-success" onclick="pay()">Pay</button>
                    </div>
                </div><!-- /.modal-content -->
            </div><!-- /.modal-dialog -->
        </div>
    <!-- /Payment QR code -->
    <script>
        function showQrCode() {
            $('#myModal').modal('hide');
            // Pop-up QR code
            $('#payModal').modal('show');
        }
        function pay() {
            /**
             * pay
             */
            if(!$('#months').val()) {
                alert('Please Input the Months!');
                return false;
            }
            $('#pay-form').submit();
        }
        var price = {{ house.price }};
        $('#months').blur(function(){
            var months = parseInt($(this).val());
            if (months <= 0) {
                alert('please input the months > 0');
                return false;
            }
            var now = moment();
            var dealine = now.add(months, 'month');
            $('#deadline').val(dealine.format('YYYY-MM-DD'));
            var r_price = price * months;
            $('#total_money').val(r_price);
        });
    </script>
{% endblock %}

mysite-house/templates/house/hetong.html
<p>Housing rental management system Contract</p>
<p>Lessor: (hereinafter called Party A) Lessee: (hereinafter called Party B) </p>
<p>In order to strengthen the standardized management of the house and clarify the rights and obligations of the lessor and lessee, in accordance with the Contract Law, the Regulations of Guangdong Province on the Administration of Commodity Exchange Market and other relevant regulations, Party A and Party B reach the following agreement on matters related to the leasing of shop (stall) in the market. </p>
<p>Article 1 Conditions and Uses of the Lease Item (See the attached table for details)</p>
<p>Article 2 Lease Term (See the attached table for details)</p>
<p>Article 3 Rental and other payments as well as the time limit and method of payment</p>
<p>(1) Rental (see the attached table for details)</p>
<p>(2) Term of rent payment:</p>
<p>Payment method: overdue payment of liquidated damages on a daily basis.</p>
<p>(3) Party B shall pay performance deposit, facility deposit and water and electricity deposit to Party A when signing this contract, which shall be used as the deposit for performance of this contract and operation standard deposit for market standard management. Upon expiration, Party B shall return or pay off the creditor's rights and debts arising out of this contract without interest.</p>
<p>(4) Party B must pay the water and electricity charges and the normal water and electricity loss contribution on time, as well as the health expenses and comprehensive security expenses on time.
Time of payment: Late fee added on a daily basis for late payment.</p>
<p>(5) Party B shall, in accordance with the provisions of national laws and regulations, implement the market food access management system such as purchase inspection, request for certificate and ticket, and make a good food import (sale) account.
If the food import (sale) account fails to be established due to objective reasons, Party A may entrust Party A to do the account, and Party A will charge the corresponding service fee and pay the payment time:.
</p>
<p>Attached Table: main contents of year lease contract</p>
<p>Main contents of lease contract alteration</p>

mysite-house/templates/house/new_search.html
{% extends "base.html" %}
{% block content %}
    <form method="get" class="form form-horizontal" style="padding-top:40px;">
        {% for exp in filter.form %}
            <div class="form-group">
                <label class="col-md-2" class="sr-only">{{ exp.label }}</label>
                <div class="col-md-8">
                    {{ exp }}
                </div>
            </div>
        {% endfor %}
        <div class=" text-center">
            <button type="submit" class="btn btn-primary">Search</button>
        </div>
    </form>
    <hr>
    <div class="result-area">
        {% load render_table from django_tables2 %}
        {% if filter.qs.count > 0 %}
            {% render_table table %}
            {% else %}
            <div class="alert alert-danger">
                Sorry, No Result!
            </div>
        {% endif %}
    </div>
    <script>
        $('input').addClass('form-control');
        $('select').addClass('form-control');
    </script>
{% endblock %}